demandai_site/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.start, name='home'),

    # Ver detalhes do item selecionado no portifolio
    path('about-portifolio/<str:action>/<int:id>', views.about_portifolio, name='about_portifolio'),

    # Cadastrar nova demanda vindo de um portifolio
    path('demandar/<str:action>/<int:id>', views.demandarSelected, name='demanda_selecionada'),

    # Cadastrar nova demanda
    path('demandar', views.demandar, name='demandar'),

    # Ver detalhes da demanda
    path('demand/detail', views.demandDetail, name='demand_detail'),

    # Login
    path('login', views.login_in, name='login'),

    # Consulta de relações
    path('search', views.search, name='search'),

    # Criar usuario
    path('user', views.user, name='user'),
    #path('search?text=<str:text>', views.search, name='search_val'),
]

projeto_demandai/urls.py
from django.conf.urls import handler404, handler500
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from projeto_demandai import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('adm/', include('demandai_administrador.urls')),
    path('', include('demandai_site.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

demandai_administrador/models.py
from django.contrib.auth.models import AbstractUser
from django.conf import settings
from django.core.validators import FileExtensionValidator
from django.db import models
from safedelete.models import SafeDeleteModel
from safedelete.models import SOFT_DELETE_CASCADE

# Create your models here.
from demandai_site.validators import validate_file_size


class Institution(SafeDeleteModel):
    _safedelete_policy = SOFT_DELETE_CASCADE

    nome = models.CharField(max_length=60)
    email = models.EmailField(max_length=50, unique=True)
    descricao = models.TextField()
    phone = models.CharField(max_length=30)
    site = models.CharField(max_length=60)
    status = models.BooleanField()
    street = models.CharField(max_length=100)
    number = models.CharField(max_length=11)
    sector = models.CharField(max_length=60)
    city = models.CharField(max_length=30)
    complement = models.CharField(max_length=60)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.nome

class Profile(AbstractUser, SafeDeleteModel):
    _safedelete_policy = SOFT_DELETE_CASCADE
    roles = (
        ('AD', 'Administrador'),
        ('SE', 'Servidor'),
        ('PE', 'Proex'),
        ('DI', 'Diem'),
        ('PI', 'Propi'),
        ('TE', 'Técnico'),
    )
    username = models.CharField(max_length=60, blank=True, null=True)
    email = models.CharField(max_length=60, unique=True)
    role = models.CharField(max_length=2, choices=roles, default='SE')
    institution = models.ForeignKey(Institution, on_delete=models.PROTECT, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    def has_permission(self, codigo):
        permissao = Permission.objects.filter(codigo=codigo).first()
        permissions_user = UserPermission.objects.filter(user_id=self.id, permission_id=permissao.id)
        return permissions_user.count() == 0

    def has_content(self, model):
        content = Content.objects.filter(model=model).first()
        content_user = UserContent.objects.filter(profile_id=self.id, content_id=content.id)
        return content_user.count() == 0

    @property
    def my_permissions(self):
        grop = []
        p = []
        dados = []
        contents = UserContent.objects.filter(profile=self.id).order_by('content')
        permissoes = UserPermission.objects.filter(user=self.id).order_by('permission')
        for cont in contents:
            content = Content.objects.get(id=cont.content_id)
            grop.append(content.model)

        for per in permissoes:
            permissao = Permission.objects.get(id=per.permission_id)
            grop.append(permissao.codigo)
        dados.append(grop)
        dados.append(p)
        return dados
    @property
    def permissions_for_menu(self):
        permissoes = UserContent.objects.filter(profile=self.id).order_by('content')
        dados = []
        for permissao in permissoes:
            content = Content.objects.get(id=permissao.content_id)
            dados.append(content)
        return dados
    def permissions_for_menu_count(self):
        permissoes = UserContent.objects.filter(profile=self.id).order_by('content')
        dados = 0
        for permissao in permissoes:
            dados = (dados+1)
        print(dados)
        return dados
    def permission_service(self):
        if self.has_content('service'):
            return False
        return True

    def create_user(self, email, date_of_birth, password=None):

        # user = self.model(
        #     email=self.normalize_email(email),
        #     date_of_birth=date_of_birth,
        # )
        #
        # user.set_password(password)
        # user.save(using=self._db)
        # return user
        return 1

    def __str__(self):
        return self.first_name +' '+ self.last_name

    def notifications(self):
        return self.notification_set.filter(visualizada=0)

    def btn_voltar_and_encaminhar(self):
         if self.has_content('prospeccao'):
             return False
         return True

class Laboratory(SafeDeleteModel):
    _safedelete_policy = SOFT_DELETE_CASCADE

    profile = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT)
    telefone = models.CharField(max_length=14)
    descricao = models.TextField()
    nome = models.CharField(max_length=30)
    atividades_realizadas = models.TextField()
    pesquisa_extensao = models.BooleanField()
    institution = models.ForeignKey(Institution, on_delete=models.PROTECT)
    endereco_sala = models.CharField(max_length=40)
    servidores = models.TextField()
    departamentos = models.TextField()
    cursos = models.TextField()
    status = models.CharField(max_length=20)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.nome

class Equipment(SafeDeleteModel):
    _safedelete_policy = SOFT_DELETE_CASCADE

    profile = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='equipments', on_delete=models.PROTECT)
    codigo = models.CharField(max_length=9)
    descricao = models.TextField()
    nome = models.CharField(max_length=30)
    institution = models.ForeignKey(Institution, on_delete=models.PROTECT)
    laboratory = models.ForeignKey(Laboratory, on_delete=models.SET_NULL, null=True)
    status = models.BooleanField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.nome

class Service(SafeDeleteModel):
    _safedelete_policy = SOFT_DELETE_CASCADE

    profile = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT)
    plataformas = models.TextField()
    descricao = models.TextField()
    nome = models.CharField(max_length=30)
    desenvolvedores = models.TextField()
    departamentos = models.TextField()
    institution = models.ForeignKey(Institution,  on_delete=models.SET_NULL, null=True)
    status = models.BooleanField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.nome

class Demand(SafeDeleteModel):
    actions = (
        ('SER', 'Serviço'),
        ('LAB', 'Laboratorio'),
        ('EQU', 'Equipamento'),
    )
    status = (
        ('S', 'Solicitada'),
        ('E', 'Em análise'),
        ('R', 'Recusada'),
        ('A', 'Aceita'),
        ('P', 'Em andamento'),
        ('V', 'Prospectada'),
        ('B', 'Respondida'),
        ('F', 'Finalizada'),
    )
    action = models.CharField(max_length=3, choices=actions)
    action_id = models.IntegerField()
    nome = models.CharField(max_length=30)
    telefone = models.CharField(max_length=16, null=True, blank=True)
    codigo = models.CharField(max_length=6)
    email = models.EmailField(max_length=40)
    descricao = models.TextField()
    # cpf = models.CharField(max_length=20)
    # data_nascimento = models.DateField()
    status = models.CharField(max_length=1, choices=status, default='S')
    file = models.FileField(upload_to="images/demand_files", null=True, blank=True, validators=[FileExtensionValidator(allowed_extensions=['zip', 'rar']), validate_file_size])
    visualizada = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    _safedelete_policy = SOFT_DELETE_CASCADE

class Demandcb(SafeDeleteModel):
    actions = (
        ('SER', 'Serviço'),
        ('LAB', 'Laboratorio'),
        ('EQU', 'Equipamento'),
    )

    demand = models.ForeignKey(Demand, on_delete=models.PROTECT)
    action = models.CharField(max_length=3, choices=actions, null=True)
    action_id = models.IntegerField(null=True)
    aceita_rejeita = models.BooleanField(null=True, default=None)

class DemandCallback(SafeDeleteModel):
    status = (
        ('S', 'Solicitado'),
        ('E', 'Analise'),
        ('R', 'Recusada'),
        ('A', 'Aceita'),
        ('P', 'Produção'),
        ('V', 'Vinculada'),
        ('B', 'FeedBack'),
        ('F', 'Finalizada'),
    )

    demand = models.ForeignKey(Demand, on_delete=models.CASCADE, default=None)
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE, default=None)
    status = models.CharField(choices=status, max_length=1, default='S')
    feedback = models.TextField()
    prazo_feedback = models.DateTimeField(null=True)
    created_at = models.DateTimeField(auto_now_add=True)

class Content(SafeDeleteModel):
    model = models.TextField()
    name = models.TextField()
    icon = models.TextField(default=None)

class Permission(SafeDeleteModel):

    permissions = (

        ('add_laboratory', 'Adicionar Laboratorio'),
        ('view_laboratory', 'Listar Laboratorio'),
        ('update_laboratory', 'Atualizar Laboratorio'),
        ('delete_laboratory', 'Deletar Laboratorio'),

        ('add_service', 'Adicionar Serviço'),
        ('view_service', 'Listar Serviço'),
        ('update_service', 'Atualizar Serviço'),
        ('delete_service', 'Deletar Serviço'),

        ('add_equipament', 'Adicionar Equipamento'),
        ('view_equipament', 'Listar Equipamento'),
        ('update_equipament', 'Atualizar Equipamento'),
        ('delete_equipament', 'Deletar Equipamento'),

        ('add_usuario', 'Adicionar Usuario'),
        ('view_usuario', 'Listar Usuario'),
        ('update_usuario', 'Atualizar Usuario'),
        ('delete_usuario', 'Deletar Usuario'),

        ('add_institution', 'Adicionar Instituição'),
        ('view_institution', 'Listar Instituição'),
        ('update_institution', 'Atualizar Instituição'),
        ('delete_institution', 'Deletar Instituição'),

        ('prospectar', 'Adicionar Instituição'),

demandai_site/forms.py
from django import forms
from django.contrib.sites.shortcuts import get_current_site

from demandai_administrador.models import Demand, Profile, Service, Laboratory, Equipment, Institution

from .mail import send_mail_template

class DemandForm(forms.ModelForm):
    file = forms.FileField(widget=forms.ClearableFileInput(attrs={'class': 'form-control'}), required=False)
    telefone = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'opcional'}), required=False)

    class Meta:
        model = Demand
        fields = ['nome', 'email', 'descricao', 'action', 'action_id', 'codigo', 'file', 'telefone']
        widgets = {
            'nome': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Informe o seu nome'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'exemplo@exemplo.com'}),
            'descricao': forms.Textarea(attrs={'class': 'form-control input-message', 'placeholder': 'Descrição da demanda'}),
            'action': forms.TextInput(attrs={'class': 'form-control', 'type': 'hidden'}),
            'action_id': forms.TextInput(attrs={'class': 'form-control', 'type': 'hidden'})
        }


    def send_mail(self, request):
        current_site = get_current_site(request)
        subject = 'Contato'
        message = 'Serviço'
        action = {}
        if self.cleaned_data['action'] == 'SER':
            action = Service.objects.get(id=self.cleaned_data['action_id'])
        elif self.cleaned_data['action'] == 'LAB':
            action = Laboratory.objects.get(id=self.cleaned_data['action_id'])
        elif self.cleaned_data['action'] == 'EQU':
            action = Equipment.objects.get(id=self.cleaned_data['action_id'])
        context = {
            'nome': self.cleaned_data['nome'],
            'descricao': self.cleaned_data['descricao'],
            'action': action.nome,
            'email': self.cleaned_data['email'],
            'codigo': self.cleaned_data['codigo'],
            'domain': current_site.domain
        }
        message = message % context

        send_mail_template(subject, 'site/email_demanda.html', context, [self.cleaned_data['email']])

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(),label='Senha')
    confirm_password = forms.CharField(widget=forms.PasswordInput(),label='Comfirme a senha')
    institution = forms.ModelChoiceField(queryset=Institution.objects.all(),widget=forms.Select(attrs={'style':'padding: 10px'}),required=True)
    first_name = forms.CharField(required=True,label='Primeiro nome')
    last_name = forms.CharField(required=True,label='Sobrenome')
    username = forms.CharField(required=True,label='Nome de Úsuario')
    class Meta:
        model = Profile
        fields = ['institution','first_name','last_name','username', 'email','password']

    def clean(self):
        cleaned_data = super(UserForm, self).clean()
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirm_password")
        if password != confirm_password:
            raise forms.ValidationError(
                "As senhas não coincidem!"
            )

templates/site/about_portifolio.html
{% extends 'site/base.html' %}
{% load static %}
{% block header %}
    <header id="header" class="header default">
  <div class="menu" id="onepagenav" style="padding: 20px 20px 20px 100px;">
  <!-- menu start -->
   <a href="{% url 'home' %}">
                    <img src="{% static "images/demandai/logo-ifto.png" %}" style="height: 150px" alt="">
                </a>
  <!-- menu end -->
 </div>
</header>
    <section class="slider-parallax typer-banner bg-overlay-black-50 parallax" style="height: 30vh;background: url({% static 'images/demandai/campus_paraiso.jpg' %});">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
      <div class="page-title-name">
{#          <h1 style="color: white">{% block title %}Sobre o portifolio{% endblock %}</h1>#}
          <p></p>
        </div>
     </div>
     </div>
  </div>
</section>
{% endblock %}

{% block banner %}{% endblock %}
{% block contact %}{% endblock %}
{% block content %}{% endblock %}

templates/site/demandar.html
{% extends 'site/about_portifolio.html' %}

{% block title %}  {% endblock %}
{% block login %}  {% endblock %}
{% load widget_tweaks %}
{% block content %}
    <div class="container">
        <div class="row mt-70">
            <div class="col-sm-12">
                {% if message %}
                    <div class="alert alert-success" role="alert">
                        Cadastrado com sucesso! Use este codigo <strong>{{ message }}</strong> para consultar sua
                        demanda, foi lhe enviado um e-mail com todas informações. Obrigado!
                    </div>
                {% endif %}
                <form action="{% url 'demandar' %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.action }}
                    {{ form.action_id }}
                    <h3 class="mb-40">Cadastre sua Demanda</h3>
                    <div class="form-row">
                        <div class="form-group col-md-4">
                            <label for="inputEmail4">Nome</label>
                            {{ form.nome }}
                            {% if form.nome.errors %}
                                <ol>
                                    {% for error in form.nome.errors %}
                                        <li class="text-danger text-errors-form"><strong>{{ error|escape }}</strong>
                                        </li>
                                    {% endfor %}
                                </ol>
                            {% endif %}
                        </div>
                        <div class="form-group col-md-4">
                            <label for="inputAddress2">E-mail</label>
                            {{ form.email }}
                            {% if form.email.errors %}
                                <ol>
                                    {% for error in form.email.errors %}
                                        <li class="text-danger text-errors-form"><strong>{{ error|escape }}</strong>
                                        </li>
                                    {% endfor %}
                                </ol>
                            {% endif %}
                        </div>
                         <div class="form-group col-md-4">
                                  <label for="inputState">Telefone</label>
                               {{ form.telefone }}
                          </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-4">
                            <label for="inputState">O que demandar?</label>
                            <select id="select-action" class="form-control" style="height: auto;">
                                <option value="SER" {% if 'SER' == dados.action %}selected{% endif %}>Serviço</option>
                                <option value="LAB" {% if 'LAB' == dados.action %}selected{% endif %}>Laboratorio
                                </option>
                                <option value="EQU" {% if 'EQU' == dados.action %}selected{% endif %}>Equipamento
                                </option>
                            </select>
                        </div>

                        <div id="ser-demand" class="form-group col-md-4">

                            <label for="inputState">Onde Demandar?</label>
                            <select onchange="changeSelectAction(this.value);" class="form-control"
                                    style="height: auto;">
                                {% for foo in dados.ser %}
                                    <option value="{{ foo.id }}"
                                            {% if foo.id == dados.action_id %}selected{% endif %}>{{ foo.nome }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div id="lab-demand" class="form-group col-md-4">
                            <label for="inputState">Onde Demandar?</label>
                            <select onchange="changeSelectAction(this.value);" class="form-control"
                                    style="height: auto;">
                                {% for foo in dados.lab %}
                                    <option value="{{ foo.id }}"
                                            {% if foo.id == dados.action_id %}selected{% endif %}>{{ foo.nome }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div id="equ-demand" class="form-group col-md-4">
                            <label for="inputState">Onde Demandar?</label>
                            <select onchange="changeSelectAction(this.value);" class="form-control"
                                    style="height: auto;">
                                {% for foo in dados.equ %}
                                    <option value="{{ foo.id }}"
                                            {% if foo.id == dados.action_id %}selected{% endif %}>{{ foo.nome }}</option>
                                {% endfor %}
                            </select>
                        </div>

                           <div class="form-group col-md-4">
                            <label class="mg-10" for="file">Enviar imagens e arquivos</label>
                            {{ form.file }}
                            {% if form.file.errors %}
                                <ul style="list-style-type:none">
                                    {% for error in form.file.errors %}
                                        <li class="text-danger text-errors-form"><strong>{{ error|escape }}</strong>
                                        </li>
                                    {% endfor %}
                                </ul>
                            {% endif %}
                        </div>

                    </div>

                    <div class="form-row">
                        <div class="section-field col-md-12">
                            <div class="textarea">
                                {{ form.descricao }}
                                {% if form.descricao.errors %}
                                    <ol>
                                        {% for error in form.descricao.errors %}
                                            <li class="text-danger text-errors-form"><strong>{{ error|escape }}</strong>
                                            </li>
                                        {% endfor %}
                                    </ol>
                                {% endif %}
                            </div>
                        </div>
                    </div>

                    <button type="submit" class="btn btn-success mt-30 mb-100"><span> Demandar </span> <i
                            class="fa fa-paper-plane"></i></button>

                </form>

            </div>
        </div>
    </div>
{% endblock %}
{% block contact %}{% endblock %}

{% block script %}
    <script type="application/javascript">
        $(document).ready(function () {
            //MASK
            $("#id_telefone").mask('(00) 0 0000-0000');
            $("#id_cpf").mask('000.000.000-00');


            var selected_init = $("#select-action option:selected").val();
            changeSelect(selected_init);
            $("#id_action").val(selected_init);
            //$("#id_action_id").val(selected_init);
            $('#select-action').change(function () {
                var selected = ($(this).val());
                changeSelect(selected);
            });
        });

        function changeSelect(selected) {
            switch (selected) {
                case 'SER':
                    $("#ser-demand").show();
                    $("#lab-demand").hide();
                    $("#equ-demand").hide();
                    $("#id_action_id").val($("#ser-demand option:selected").val());
                    $("#id_action").val('SER');
                    break;
                case 'LAB':
                    $("#ser-demand").hide();
                    $("#lab-demand").show();
                    $("#equ-demand").hide();
                    $("#id_action").val('LAB');
                    $("#id_action_id").val($("#lab-demand option:selected").val());

                    break;
                case 'EQU':
                    $("#ser-demand").hide();
                    $("#lab-demand").hide();
                    $("#equ-demand").show();
                    $("#id_action_id").val($("#equ-demand option:selected").val());
                    $("#id_action").val('EQU');
                    break;
            }
        }

        function changeSelectAction(id) {
            $("#id_action_id").val(id);
        }
    </script>
{% endblock %}

templates/site/index.html
{% extends 'site/base.html' %}
{% block content %}
    <!--=================================
     About-->
    {% block about %}
        {% include 'site/about.html' %}
    {% endblock %}
    <!--=================================
     About-->

     <!--=================================
    counter-->
    {% block counter %}
        {% include 'site/counter.html' %}
    {% endblock %}
    <!--=================================
    counter-->

    <!--=================================
    key features  -->
    {% block services %}
        {% include 'site/services.html' %}
    {% endblock %}
    <!--=================================
    key features -->

    <!--=================================
     portfolio -->
    {% block portfolio %}
        {% include 'site/portfolio.html' %}
    {% endblock %}
    <!--=================================
     portfolio -->
{% endblock %}

templates/site/modal_login.html
    <!--=================================
modal -->
    {% load static %}
    <!--=================================
modal -->
    <style>
        .modal-dialog {
            min-height: calc(100vh - 200px);
            display: flex;
            flex-direction: column;
            justify-content: center;
            overflow: auto;
            width: 430px;
        }

        @media(max-width: 768px) {
            .modal-dialog {
                min-height: calc(100vh - 200px);
            }
        }
       
    </style>
    <section>
        <div class="container">
            <div class="col-lg-12">
                <div class="modal fade" id="loginModal" tabindex="-1" role="dialog"
                    aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content login-bg clearfix">
                            <div class="login-title text-center">
                                <h2 class="text-white mb-0">Faça login na sua conta</h2>
                            </div>
                            <form action="{% url 'login' %}" method="post">
                                {% csrf_token %}
                            <div class="login-form">
                                <div class="form-row mb-20">
                                    <label class="mb-10" for="name">E-mail* </label>
                                    <input type="text" name="email" class="web form-control" placeholder="example@example.com" maxlength="254" id="id_email">

                                </div>
                                <div class="form-group mb-20">
                                    <label class="mb-10" for="Password">Senha* </label>
                                    <input type="password" name="password" class="Password form-control" placeholder="senha" maxlength="128" required="" id="id_password">
                                </div>
                                <div class="form-group">
                                    <div class="remember-checkbox mb-30">
                                        <input type="checkbox" class="form-control" name="conection_permanent" id="two" />
                                        <label for="two"> Lembrar-me</label>
                                        <a href="#" class="float-right">Esqueceu sua senha?</a>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <button type="submit" class="button mt-5">
                                        <span>Acessar </span>
                                        <i class="fa fa-check"></i>
                                    </button>
                                    <a class="button btn-info" href="{% url 'user' %}">
                                        <span>Cadastre-se</span>
                                        <i class="fa fa-check"></i>
                                    </a>
                                </div>
                            </div>
                                </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section>
        <div class="container">
            <div class="col-lg-12">
                <div class="modal fade" id="consultarDemanda" tabindex="-1" role="dialog"
                    aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content login-bg clearfix">
                            <div class="login-title text-center">
                                <h2 class="text-white mb-0">Consultar Demanda</h2>
                            </div>
                            <form action="{% url 'demand_detail' %}" method="get">
                                {% csrf_token %}
                            <div class="login-form">
                                <div class="form-row mb-20">
                                    <label class="mb-10" for="email">E-mail </label>
                                    <input type="email" name="email" class="web form-control" placeholder="example@example.com" id="email" required>

                                </div>
                                <div class="form-group mb-20">
                                    <label class="mb-10" for="Password">Codigo </label>
                                    <input type="text" name="codigo" class="Password form-control" placeholder="XX00X0" maxlength="128" required="" id="id_codigo">
                                </div>

                                <button type="submit" class="button btn-block mt-10">
                                    <span>Consultar </span>
                                    <i class="fa fa-check"></i>
                                </button>

                            </div>
                                </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

templates/site/progress.html
{% load static %}

<section class="page-section-ptb parallax"  style="margin-bottom: 60px;">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 sm-mb-30">
               <img class="img-fluid" src="{% static 'images/demandai/etapas.png' %}" alt="">
            </div>
        </div>
    </div>
</section>